### 회원가입
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "pass1234",
  "nickname": "테스트1"
}


### 로그인
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "pass1234"
}


### 내 정보 조회 (JWT 필요)
# 아래 토큰은 로그인 응답에서 받은 token 값으로 바꾸기
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImVtYWlsIjoidGVzdDFAZXhhbXBsZS5jb20iLCJuaWNrbmFtZSI6Iu2FjOyKpO2KuDEiLCJpYXQiOjE3NjM1MzYwMjgsImV4cCI6MTc2MzUzOTYyOH0.8dM32P-n1ajKwNXwCJTTqzHoXo_v5C_twyACn3YpxOM